/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExampleRouteImport } from './routes/example'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExampleIndexRouteImport } from './routes/example/index'
import { Route as ExampleFocusRouteImport } from './routes/example/focus'

const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleIndexRoute = ExampleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExampleRoute,
} as any)
const ExampleFocusRoute = ExampleFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => ExampleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/example': typeof ExampleRouteWithChildren
  '/example/focus': typeof ExampleFocusRoute
  '/example/': typeof ExampleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/example/focus': typeof ExampleFocusRoute
  '/example': typeof ExampleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/example': typeof ExampleRouteWithChildren
  '/example/focus': typeof ExampleFocusRoute
  '/example/': typeof ExampleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/example' | '/example/focus' | '/example/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/example/focus' | '/example'
  id: '__root__' | '/' | '/docs' | '/example' | '/example/focus' | '/example/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  ExampleRoute: typeof ExampleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/': {
      id: '/example/'
      path: '/'
      fullPath: '/example/'
      preLoaderRoute: typeof ExampleIndexRouteImport
      parentRoute: typeof ExampleRoute
    }
    '/example/focus': {
      id: '/example/focus'
      path: '/focus'
      fullPath: '/example/focus'
      preLoaderRoute: typeof ExampleFocusRouteImport
      parentRoute: typeof ExampleRoute
    }
  }
}

interface ExampleRouteChildren {
  ExampleFocusRoute: typeof ExampleFocusRoute
  ExampleIndexRoute: typeof ExampleIndexRoute
}

const ExampleRouteChildren: ExampleRouteChildren = {
  ExampleFocusRoute: ExampleFocusRoute,
  ExampleIndexRoute: ExampleIndexRoute,
}

const ExampleRouteWithChildren =
  ExampleRoute._addFileChildren(ExampleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  ExampleRoute: ExampleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
